---
title: " "
author:
- familyname: YANG
  othernames: Mengyuan
  address: Monash University
  email: "myan0065@student.monash.edu"
  correspondingauthor: true
  qualifications:  Master of Business Analytics
- familyname: BATSAIKHAN
  othernames: Zoljargal
  address: Monash University
  email: "zbat0001@student.monash.edu"
  correspondingauthor: true
  qualifications: Master of Business Analytics
- familyname: WANG
  othernames: Xinrui
  address: Monash University
  email: "xwan0274@student.monash.edu"
  correspondingauthor: true
  qualifications: Master of Business Analytics
- familyname: GOH
  othernames: Xueqi
  address: MONASH UNIVERSITY
  email: "xgoh0002@student.monash.edu"
  correspondingauthor: true
  qualifications: Master of Business Analytics
department: Our consultancy \newline Mengyuan YANG &\newline Zoljargal BATSAIKHAN &\newline Xinrui WANG &\newline Xueqi GOH
organization: Monash University
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: true
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries
library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(ggplot2)
library(gridExtra)
library(tinytex)
library(readxl)
library(naniar)
```


\section*{Introduction}

```{r}
excel_sheets("data/API_4_DS2_en_excel_v2_2252569.xls")

data_income <- read_excel("data/CLASS.xls", range = anchored("C5", dim = c(220,5))) %>% 
  select(-X) %>% 
  filter(Economy != "x")
```

```{r}
df<- read_excel("Data/API_4_DS2_en_excel_v2_2252569.xls", sheet = 1, range = "A4:BM42772") %>% 
  select("Country Name", 
         "Country Code",
         "Indicator Name", 
         "2000":"2019") %>% 
  rename("country_name" = "Country Name",
         "indicator" = "Indicator Name",
         "country_code" = "Country Code")
```


```{r}
df %>%
  group_by(country_name) %>%
  miss_var_summary() %>% 
  arrange(-pct_miss)
```

```{r}
df_filter <- df %>% 
  filter(!(country_name %in% c("Faroe Islands",
                          "Greenland",
                          "Isle of Man",
                          "Not classified",
                          "St. Martin (French part)",
                          "Northern Mariana Islands",
                          "Kosovo",
                          "American Samoa",
                          "Gibraltar",
                          "Sint Maarten (Dutch part)",
                          "Turks and Caicos Islands",
                          "Channel Islands",
                          "Guam",
                          "French Polynesia",
                          "Curacao",
                          "New Caledonia",
                          "Virgin Islands (U.S.)",
                          "Nauru",
                          "Palau",
                          "Somalia",
                          "Guinea-Bissau")))
       
```

```{r}
data_joined <- df_filter %>% 
    left_join(data_income, by = c("country_name" = "Economy",
                                "country_code" = "Code")) 
```

\section*{Mengyun}


\section*{Zoljargal}

```{r}
data_gdp <- read_excel("data/GDPpercapita.xls", range = anchored("A4", dim = c(265,64))) %>% 
  select("Country Name", 
         "Country Code", 
         "2000":"2019") %>% 
  rename("country_name" = "Country Name",
         "country_code" = "Country Code") %>% 
  pivot_longer(cols = "2000":"2019",
               names_to = "year",
               values_to = "GDPpercapita")

data_zb <- data_joined %>% 
  pivot_longer(cols = c("2000":"2019"),
               names_to = "year",
               values_to = "value") %>% 
  filter(indicator %in% c("Government expenditure on education, total (% of GDP)",
                          "Government expenditure on education, total (% of government expenditure)",
                          "Expenditure on secondary education (% of government expenditure on education)",
                          "Government expenditure per student, secondary (% of GDP per capita)",
                          "Expenditure on primary education (% of government expenditure on education)",
                          "Government expenditure per student, primary (% of GDP per capita)")) %>% 
  pivot_wider(names_from = indicator,
              values_from = value) %>% 
  drop_na(Region) %>% 
  rename("income_group" = "Income group",
         "region" = "Region")

selected_indicators = c("Government expenditure on education, total (% of GDP)",
                          "Government expenditure on education, total (% of government expenditure)",
                          "Expenditure on secondary education (% of government expenditure on education)",
                          "Government expenditure per student, secondary (% of GDP per capita)",
                          "Expenditure on primary education (% of government expenditure on education)",
                          "Government expenditure per student, primary (% of GDP per capita)")

new_name = c("ex_total_GDP",
             "ex_total_gov_ex",
             "ex_secondary",
             "ex_per_student_secondary",
             "ex_primary",
             "ex_per_student_primary")

for(i in 1:6) names(data_zb)[names(data_zb) == selected_indicators[i]] = new_name[i]

data_zb$country_name[which(data_zb$country_name == "United States")] = "USA"
data_zb$country_name[which(data_zb$country_name == "United Kingdom")] = "UK"
data_zb$country_name[which(data_zb$country_name == "Russian Federation")] = "Russia"
data_zb$country_name[which(data_zb$country_name == "Iran, Islamic Rep.")] = "Iran"
data_zb$country_name[which(data_zb$country_name == "Congo, Rep.")] = "Democratic Republic of the Congo"
data_zb$country_name[which(data_zb$country_name == "Venezuela, RB")] = "Venezuela"
data_zb$country_name[which(data_zb$country_name == "Yemen, Rep.")] = "Yemen"
data_zb$country_name[which(data_zb$country_name == "Egypt, Arab Rep.")] = "Egypt"

data_zb <- data_zb %>% 
  left_join(data_gdp, by = c("country_name", "country_code", "year"))
```

```{r plot1-zb fig.cap = "Government expenditure on education (% of GDP), 2000-2019"}
data1_zb <- data_zb %>% 
  group_by(country_name) %>% 
  summarise(mean = mean(ex_total_GDP, na.rm = TRUE))

world_map <- map_data("world")

data1_zb_wm <- world_map %>% 
  left_join(data1_zb, by = c("region" = "country_name"))

data1_zb_wm %>% 
  ggplot(aes(long, lat, group = group))+
  geom_polygon(aes(fill = mean), color = "white")+
  scale_fill_viridis_c(option = "C") 
```

```{r}
data2_zb <- data_zb %>% 
  filter(year != "2019") %>% 
  group_by(income_group, year) %>% 
  summarise(mean = mean(ex_total_GDP, na.rm = TRUE))

ggplot(data2_zb, aes(x=year, y=mean, group = income_group)) + 
    geom_line(aes(color = income_group)) +
  geom_point(aes(color = income_group))
```

```{r}
data3_zb <- data_zb %>% 
  filter(year != "2019",
         region != "North America") %>% 
  group_by(region, year) %>% 
  summarise(mean = mean(ex_total_GDP, na.rm = TRUE)) 

data3_zb %>% 
  ggplot(aes(x=year, y=mean, group = region)) + 
    geom_line(aes(color = region)) +
  geom_point(aes(color = region))

```

```{r}
data_zb %>% 
  filter(year != "2019") %>% 
  group_by(income_group, year) %>% 
  summarise(mean = mean(ex_total_GDP, na.rm = TRUE)) %>% 
  pivot_wider(names_from = year,
              values_from = mean) %>% 
  select(income_group, "2000", "2015") %>% 
  kable(col.names = c("Income groups", 
                      "2000",
                      "2015"),
        align = "c",
        caption = "Total government expenditure on educationby income group in 2000 and 2015",
        digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

```

```{r}

```

\section*{Xinrui}


\section*{Xueqi}


\section*{Conclusion}

